events {}

http {
  server {
    listen 80;

    location / {
      # "app" wordt opgelost via Swarm service-DNS naar een VIP
      # die over alle app-replicas load-balanced.
      proxy_pass http://app:8000;
    }
  }
}
